[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.15.1",
    "bcrypt>=4.3.0",
    "fastapi>=0.115.11",
    "minio>=7.2.15",
    "passlib>=1.7.4",
    "psycopg>=3.2.6",
    "pydantic-settings>=2.8.1",
    "python-jose>=3.4.0",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "sqlalchemy-utils>=0.41.2",
    "uvicorn>=0.34.0",
]
